import { useContext } from "react";
import Icon from "../icon/icon";
import { ThemeContext } from "../../context/themeContext";

export function styleTheme(type, colors) {
  const [theme, setTheme] = useContext(ThemeContext);
  const values = {
    text: {
      light: colors[0] ? "text-" + colors[0] : "",
      dark: colors[1] ? "text-" + colors[1] : "text-white",
    },
    bg: {
      light: colors[0] ? "bg-" + colors[0] : "bg-white",
      dark: colors[1] ? "bg-" + colors[1] : "bg-black",
    },
    border: {
      light: colors[0] ? "border-" + colors[0] : "",
      dark: colors[1] ? "border-" + colors[1] : "border-white",
    },
  };
  return values[type][theme];
}

export function styleRadius(base, radius, level?) {
  console.log([base, level, radius].join(" "));
  if (level) {
    const values = {
      button: {
        main: {
          none: "!rounded-none",
          full: "!rounded-full",
          diagonal:
            "!rounded-tl-3xl !rounded-tr-md !rounded-br-3xl !rounded-bl-md",
          sm: "!rounded-sm",
          lg: "!rounded-2xl",
        },
        secondary: {
          none: "!rounded-none",
          full: "!rounded-full",
          diagonal:
            "!rounded-tl-lg !rounded-tr-sm !rounded-br-lg !rounded-bl-sm",
          sm: "!rounded-sm",
          lg: "!rounded-lg",
        },
      },
      form: {
        main: {
          none: "!rounded-none",
          full: "!rounded-full",
          diagonal:
            "!rounded-tl-3xl !rounded-tr-md !rounded-br-3xl !rounded-bl-md",
          sm: "!rounded-sm",
          lg: "!rounded-2xl",
        },
        secondary: {
          none: "!rounded-none",
          full: "!rounded-full",
          diagonal:
            "!rounded-tl-lg !rounded-tr-sm !rounded-br-lg !rounded-bl-sm",
          sm: "!rounded-sm",
          lg: "!rounded-lg",
        },
      },
      icon: {
        main: {
          none: "!rounded-none",
          full: "!rounded-full",
          diagonal:
            "!rounded-tl-3xl !rounded-tr-md !rounded-br-3xl !rounded-bl-md",
          sm: "!rounded-sm",
          lg: "!rounded-2xl",
        },
        secondary: {
          none: "!rounded-none",
          full: "!rounded-full",
          diagonal:
            "!rounded-tl-lg !rounded-tr-sm !rounded-br-lg !rounded-bl-sm",
          sm: "!rounded-sm",
          lg: "!rounded-lg",
        },
      },
      images: {
        bg: {
          none: "!rounded-none",
          full: "!rounded-full",
          diagonal:
            "!rounded-tl-lg !rounded-tr-sm !rounded-br-lg !rounded-bl-sm",
          sm: "!rounded-sm",
          lg: "!rounded-lg",
        },
        navbar: {
          none: "!rounded-none",
          full: "!rounded-full",
          diagonal:
            "!rounded-tl-lg !rounded-tr-sm !rounded-br-lg !rounded-bl-sm",
          sm: "!rounded-sm",
          lg: "!rounded-lg",
        },
        defaultProfile: {
          none: "!rounded-none",
          full: "!rounded-full",
          diagonal:
            "!rounded-tl-lg !rounded-tr-sm !rounded-br-lg !rounded-bl-sm",
          sm: "!rounded-sm",
          lg: "!rounded-lg",
        },
      },
    };
    return values[base][level][radius];
  } else {
    const values = {
      block: {
        none: "!rounded-none",
        full: "!rounded-full",
        diagonal: "rounded-tl-3xl rounded-bl-md rounded-tr-md rounded-br-3xl",
        sm: "!rounded-lg",
        lg: "!rounded-3xl",
      },
      image: {
        none: "!rounded-none",
        full: "!rounded-full",
        diagonal:
          "!rounded-tl-[5rem] !rounded-tr-2xl !rounded-br-[5rem] !rounded-bl-2xl",
        sm: "!rounded-lg",
        lg: "!rounded-3xl",
      },
      mainComponent: {
        none: "!rounded-none",
        full: "!rounded-full",
        diagonal: "rounded-tl-3xl rounded-bl-md rounded-tr-md rounded-br-3xl",
        sm: "!rounded-lg",
        lg: "!rounded-3xl",
      },
      modal: {
        none: "!rounded-none",
        full: "!rounded-full",
        diagonal: "rounded-tl-3xl rounded-bl-md rounded-tr-md rounded-br-3xl",
        sm: "!rounded-lg",
        lg: "!rounded-3xl",
      },

      navbar: {
        none: "!rounded-none",
        full: "!rounded-full",
        diagonal: "rounded-tl-3xl rounded-bl-md rounded-tr-md rounded-br-3xl",
        sm: "!rounded-lg",
        lg: "!rounded-3xl",
      },
      offcanvas: {
        none: "!rounded-none",
        full: "!rounded-full",
        diagonal: "rounded-tl-3xl rounded-bl-md rounded-tr-md rounded-br-3xl",
        sm: "!rounded-lg",
        lg: "!rounded-3xl",
      },
      secondaryComponent: {
        none: "!rounded-none",
        full: "!rounded-full",
        diagonal:
          "!rounded-tl-3xl !rounded-bl-md !rounded-tr-md !rounded-br-3xl",
        sm: "!rounded-lg",
        lg: "!rounded-3xl",
      },
      specialComponent: {
        none: "!rounded-none",
        full: "!rounded-full",
        diagonal:
          "!rounded-tl-3xl !rounded-bl-md !rounded-tr-md !rounded-br-3xl",
        sm: "!rounded-lg",
        lg: "!rounded-3xl",
      },
    };
    return values[base][radius];
  }
}

// export function styleBg(base, bg, level?) {
//   if (level) {
//     const values = {
//       button:
//       form:
//       icon:
//     };
//     return values[base][level][bg];
//   } else {
//     const values = {
//       mainComponent:
//       secondaryComponent:
//       specialComponent:
//       block:
//       modal:
//       offcanvas:
//       navbar:
//     };
//     return values[base][bg];
//   }
// }

export function styleShadow(base, shadow, level?) {
  if (level) {
    const values = {
      button: {
        main: {
          none: "!drop-shadow-none",
          sm: "!drop-shadow-md",
          md: "!drop-shadow-lg",
          lg: "!drop-shadow-2xl",
          intern: "!shadow-[inset_0_3px_6px_-1px_rgba(0,0,0,0.3)]",
        },
        secondary: {
          none: "!drop-shadow-none",
          sm: "!drop-shadow-md",
          md: "!drop-shadow-lg",
          lg: "!drop-shadow-2xl",
          intern: "!shadow-[inset_0_3px_6px_-1px_rgba(0,0,0,0.3)]",
        },
      },
      text: {
        main: {
          none: "!drop-shadow-none",
          sm: "!drop-shadow-md",
          md: "!drop-shadow-lg",
          lg: "!drop-shadow-2xl",
          intern: "!shadow-[inset_0_3px_6px_-1px_rgba(0,0,0,0.3)]",
        },
        secondary: {
          none: "!drop-shadow-none",
          sm: "!drop-shadow-md",
          md: "!drop-shadow-lg",
          lg: "!drop-shadow-2xl",
          intern: "!shadow-[inset_0_3px_6px_-1px_rgba(0,0,0,0.3)]",
        },
        base: {
          none: "!drop-shadow-none",
          sm: "!drop-shadow-md",
          md: "!drop-shadow-lg",
          lg: "!drop-shadow-2xl",
          intern: "!shadow-[inset_0_3px_6px_-1px_rgba(0,0,0,0.3)]",
        },
        sub: {
          none: "!drop-shadow-none",
          sm: "!drop-shadow-md",
          md: "!drop-shadow-lg",
          lg: "!drop-shadow-2xl",
          intern: "!shadow-[inset_0_3px_6px_-1px_rgba(0,0,0,0.3)]",
        },
        form: {
          main: {
            none: "!drop-shadow-none",
            sm: "!drop-shadow-md",
            md: "!drop-shadow-lg",
            lg: "!drop-shadow-2xl",
            intern: "!shadow-[inset_0_3px_6px_-1px_rgba(0,0,0,0.3)]",
          },
          secondary: {
            none: "!drop-shadow-none",
            sm: "!drop-shadow-md",
            md: "!drop-shadow-lg",
            lg: "!drop-shadow-2xl",
            intern: "!shadow-[inset_0_3px_6px_-1px_rgba(0,0,0,0.3)]",
          },
        },
        icon: {
          main: {
            none: "!drop-shadow-none",
            sm: "!drop-shadow-md",
            md: "!drop-shadow-lg",
            lg: "!drop-shadow-2xl",
            intern: "!shadow-[inset_0_3px_6px_-1px_rgba(0,0,0,0.3)]",
          },
          secondary: {
            none: "!drop-shadow-none",
            sm: "!drop-shadow-md",
            md: "!drop-shadow-lg",
            lg: "!drop-shadow-2xl",
            intern: "!shadow-[inset_0_3px_6px_-1px_rgba(0,0,0,0.3)]",
          },
        },
        images: {
          bg: {
            none: "!drop-shadow-none",
            sm: "!drop-shadow-md",
            md: "!drop-shadow-lg",
            lg: "!drop-shadow-2xl",
            intern: "!shadow-[inset_0_3px_6px_-1px_rgba(0,0,0,0.3)]",
          },
          navbar: {
            none: "!drop-shadow-none",
            sm: "!drop-shadow-md",
            md: "!drop-shadow-lg",
            lg: "!drop-shadow-2xl",
            intern: "!shadow-[inset_0_3px_6px_-1px_rgba(0,0,0,0.3)]",
          },
          defaultProfile: {
            none: "!drop-shadow-none",
            sm: "!drop-shadow-md",
            md: "!drop-shadow-lg",
            lg: "!drop-shadow-2xl",
            intern: "!shadow-[inset_0_3px_6px_-1px_rgba(0,0,0,0.3)]",
          },
        },
      },
    };
    return values[base][level][shadow];
  } else {
    const values = {
      image: {
        none: "!drop-shadow-none",
        sm: "!drop-shadow-md",
        md: "!drop-shadow-lg",
        lg: "!drop-shadow-2xl",
        intern: "!shadow-[inset_0_3px_6px_-1px_rgba(0,0,0,0.3)]",
      },
      mainComponent: {
        none: "!drop-shadow-none",
        sm: "!drop-shadow-md",
        md: "!drop-shadow-lg",
        lg: "!drop-shadow-2xl",
        intern: "!shadow-[inset_0_3px_6px_-1px_rgba(0,0,0,0.3)]",
      },
      secondaryComponent: {
        none: "!drop-shadow-none",
        sm: "!drop-shadow-md",
        md: "!drop-shadow-lg",
        lg: "!drop-shadow-2xl",
        intern: "!shadow-[inset_0_3px_6px_-1px_rgba(0,0,0,0.3)]",
      },
      specialComponent: {
        none: "!drop-shadow-none",
        sm: "!drop-shadow-md",
        md: "!drop-shadow-lg",
        lg: "!drop-shadow-2xl",
        intern: "!shadow-[inset_0_3px_6px_-1px_rgba(0,0,0,0.3)]",
      },
      block: {
        none: "!drop-shadow-none",
        sm: "!drop-shadow-md",
        md: "!drop-shadow-lg",
        lg: "!drop-shadow-2xl",
        intern: "!shadow-[inset_0_3px_6px_-1px_rgba(0,0,0,0.3)]",
      },
      modal: {
        none: "!drop-shadow-none",
        sm: "!drop-shadow-md",
        md: "!drop-shadow-lg",
        lg: "!drop-shadow-2xl",
        intern: "!shadow-[inset_0_3px_6px_-1px_rgba(0,0,0,0.3)]",
      },
      offcanvas: {
        none: "!drop-shadow-none",
        sm: "!drop-shadow-md",
        md: "!drop-shadow-lg",
        lg: "!drop-shadow-2xl",
        intern: "!shadow-[inset_0_3px_6px_-1px_rgba(0,0,0,0.3)]",
      },
      navbar: {
        none: "!drop-shadow-none",
        sm: "!drop-shadow-md",
        md: "!drop-shadow-lg",
        lg: "!drop-shadow-2xl",
        intern: "!shadow-[inset_0_3px_6px_-1px_rgba(0,0,0,0.3)]",
      },
    };
    return values[base][shadow];
  }
}

export function styleIcon(style, name, size) {
  const values = {
    default: {
      home: ["", ""],
      shop: ["", ""],
      language: ["", ""],
      arrowLeft: ["", ""],
      arrowRight: ["", ""],
      search: ["", ""],
      confirm: ["", ""],
      cancel: ["", ""],
      star: ["", ""],
      product: ["", ""],
      setting: ["", ""],
      menu: ["", ""],
      list: ["", ""],
      grid: ["", ""],
      brightness: ["", ""],
      darkness: ["", ""],
      login: ["", ""],
      logout: ["", ""],
      add: ["", ""],
      less: ["", ""],
      view: ["", ""],
      edit: ["", ""],
      erase: ["", ""],
      card: ["", ""],
      money: ["", ""],
      close: ["", ""],
      open: ["", ""],
      upload: ["", ""],
      confetti: ["", ""],
      password: ["", ""],
      chart: ["", ""],
      receipt: ["", ""],
      share: ["", ""],
      heart: ["", ""],
      id: ["", ""],
      profile: ["", ""],
      file: ["", ""],
      email: ["", ""],
      return: ["", ""],
      qr: ["", ""],
      quote: ["", ""],
      alert: ["", ""],
      send: ["", ""],
      wallet: ["", ""],
      warning: ["", ""],
      like: ["", ""],
      dislike: ["", ""],
      tag: ["", ""],
      filter: ["", ""],
      annex: ["", ""],
      calendar: ["", ""],
      calc: ["", ""],
      photo: ["", ""],
      image: ["", ""],
      comment: ["", ""],
    },
    fill: {
      home: ["bs", "BsFillHouseFill"],
      shop: ["ri", "RiShoppingBag3Fill"],
      language: ["ti", "TiGlobe"],
      arrowLeft: ["", ""],
      arrowRight: ["", ""],
      search: ["ri", "RiSearchEyeFill"],
      confirm: ["", ""],
      cancel: ["", ""],
      star: ["tb", "TbStarFilled"],
      product: ["", ""],
      setting: ["ri", "RiSettings3Fill"],
      menu: ["", ""],
      list: ["", ""],
      grid: ["", ""],
      brightness: ["ri", "RiSunFill"],
      darkness: ["ri", "RiMoonClearFill"],
      login: ["", ""],
      logout: ["", ""],
      add: ["fa", "FaPlus"],
      less: ["fa", "FaMinus"],
      view: ["ri", "RiEye2Fill"],
      edit: ["pi", "PiPencilSimpleLineFill"],
      erase: ["tb", "TbTrashFilled"],
      card: ["bs", "BsFillCreditCardFill"],
      money: ["pi", "PiMoneyFill"],
      close: ["", ""],
      open: ["", ""],
      upload: ["", ""],
      confetti: ["pi", "PiConfettiFill"],
      password: ["pi", "PiPasswordFill"],
      chart: ["", ""],
      receipt: ["", ""],
      share: ["", ""],
      heart: ["ri", "RiHeart2Fill"],
      id: ["bs", "BsFillPersonVcardFill"],
      profile: ["ri", "RiAccountCircleFill"],
      file: ["pi", "PiFolderOpenFill"],
      email: ["", ""],
      return: ["", ""],
      qr: ["", ""],
      quote: ["", ""],
      alert: ["ai", "AiFillAlert"],
      send: ["", ""],
      wallet: ["ri", "RiWallet3Fill"],
      warning: ["tb", "TbAlertTriangleFilled"],
      like: ["ri", "RiThumbUpFill"],
      dislike: ["ri", "RiThumbDownFill"],
      tag: ["bs", "BsFillTagFill"],
      filter: ["ri", "RiFilter2Fill"],
      annex: ["", ""],
      calendar: ["", ""],
      calc: ["bs", "BsCalculatorFill"],
      photo: ["ri", "RiPhoneCameraFill"],
      image: ["bs", "BsImageFill"],
      comment: ["", ""],
    },
    thin: {
      home: ["pi", "PiHouseThin"],
      shop: ["pi", "PiHandbagThin"],
      language: ["pi", "PiTranslateThin"],
      arrowLeft: ["pi", "PiArrowCircleLeftThin"],
      arrowRight: ["pi", "PiArrowCircleRightThin"],
      search: ["pi", "PiMagnifyingGlassThin"],
      confirm: ["pi", "PiCheckFatThin"],
      cancel: ["pi", "PiProhibitInsetThin"],
      star: ["pi", "PiStarThin"],
      product: ["pi", "PiGiftThin"],
      setting: ["pi", "PiGearThin"],
      menu: ["pi", "PiDotsThreeCircleThin"],
      list: ["pi", "PiListDashesThin"],
      grid: ["pi", "PiGridFourThin"],
      brightness: ["pi", "PiSunDimThin"],
      darkness: ["pi", "PiMoonStarsThin"],
      login: ["pi", "PiSignInThin"],
      logout: ["pi", "PiSignOutThin"],
      add: ["pi", "PiPlusCircleThin"],
      less: ["pi", "PiMinusCircleThin"],
      view: ["pi", "PiEyeThin"],
      edit: ["pi", "PiPencilLineThin"],
      erase: ["pi", "PiTrashThin"],
      card: ["pi", "PiCreditCardThin"],
      money: ["pi", "PiPiggyBankThin"],
      close: ["pi", "PiXCircleThin"],
      open: ["pi", "PiArrowSquareInThin"],
      upload: ["pi", "PiUploadSimpleThin"],
      confetti: ["pi", "PiConfettiThin"],
      password: ["pi", "PiPasswordThin"],
      chart: ["pi", "PiChartPieSliceThin"],
      receipt: ["pi", "PiReceiptThin"],
      share: ["pi", "PiShareNetworkThin"],
      heart: ["pi", "PiHeartThin"],
      id: ["pi", "PiFingerprintThin"],
      profile: ["pi", "PiUserCircleThin"],
      file: ["pi", "PiFolderNotchOpenThin"],
      email: ["pi", "PiEnvelopeThin"],
      return: ["pi", "PiArrowUDownLeftThin"],
      qr: ["pi", "PiQrCodeThin"],
      quote: ["pi", "PiQuotesThin"],
      alert: ["pi", "PiSirenThin"],
      send: ["pi", "PiPaperPlaneTiltThin"],
      wallet: ["pi", "PiWalletThin"],
      warning: ["pi", "PiWarningCircleThin"],
      like: ["pi", "PiThumbsUpThin"],
      dislike: ["pi", "PiThumbsDownThin"],
      tag: ["pi", "PiTagThin"],
      filter: ["pi", "PiSlidersThin"],
      annex: ["pi", "PiPaperclipThin"],
      calendar: ["pi", "PiCalendarBlankThin"],
      calc: ["pi", "PiCalculatorThin"],
      photo: ["pi", "PiCameraThin"],
      image: ["pi", "PiImageThin"],
      comment: ["pi", "PiChatCircleDotsThin"],
    },
    square: {
      home: ["ri", "RiHomeFill"],
      shop: ["ri", "RiShoppingBag2Fill"],
      language: ["pi", "PiTranslateFill"],
      arrowLeft: ["bi", "BiSolidChevronLeftSquare"],
      arrowRight: ["bi", "BiSolidChevronRightSquare"],
      search: ["", ""],
      confirm: ["bi", "BiSolidCheckSquare"],
      cancel: ["bi", "BiSolidXSquare"],
      star: ["", ""],
      product: ["", ""],
      setting: ["pi", "PiNutFill"],
      menu: ["", ""],
      list: ["pi", "PiSquareSplitVerticalFill"],
      grid: ["pi", "PiSquaresFourFill"],
      brightness: ["", ""],
      darkness: ["", ""],
      login: ["hi", "HiMiniArrowDownOnSquare"],
      logout: ["hi", "HiMiniArrowUpOnSquare"],
      add: ["bi", "BiSolidPlusSquare"],
      less: ["bi", "BiSolidMinusSquare"],
      view: ["", ""],
      edit: ["ri", "RiEditBoxFill"],
      erase: ["", ""],
      card: ["ri", "RiBankCardFill"],
      money: ["ri", "RiCashFill"],
      close: ["", ""],
      open: ["", ""],
      upload: ["", ""],
      confetti: ["", ""],
      password: ["pi", "PiLockSimpleFill"],
      chart: ["fa", "FaSquarePollVertical"],
      receipt: ["", ""],
      share: ["fa", "FaShareAltSquare"],
      heart: ["bi", "BiSolidHeartSquare"],
      id: ["", ""],
      profile: ["", ""],
      file: ["", ""],
      email: ["ri", "RiMailFill"],
      return: ["", ""],
      qr: ["pi", "PiQrCodeFill"],
      quote: ["bs", "BsChatSquareQuoteFill"],
      alert: ["bs", "BsFillExclamationSquareFill"],
      send: ["fa", "FaShareSquare"],
      wallet: ["pi", "PiCardholderFill"],
      warning: ["", ""],
      like: ["", ""],
      dislike: ["", ""],
      tag: ["ri", "RiPriceTagFill"],
      filter: ["bs", "BsFilterSquareFill"],
      annex: ["ri", "RiAttachmentFill"],
      calendar: ["", ""],
      calc: ["ri", "RiCalculatorFill"],
      photo: ["", ""],
      image: ["", ""],
      comment: ["", ""],
    },
    rounded: {
      home: ["", ""],
      shop: ["", ""],
      language: ["", ""],
      arrowLeft: ["tb", "TbSquareRoundedChevronLeftFilled"],
      arrowRight: ["tb", "TbSquareRoundedChevronRightFilled"],
      search: ["tb", "TbZoomFilled"],
      confirm: ["tb", "TbSquareRoundedCheckFilled"],
      cancel: ["tb", "TbSquareRoundedXFilled"],
      star: ["", ""],
      product: ["", ""],
      setting: ["", ""],
      menu: ["", ""],
      list: ["", ""],
      grid: ["", ""],
      brightness: ["", ""],
      darkness: ["", ""],
      login: ["", ""],
      logout: ["", ""],
      add: ["tb", "TbSquareRoundedPlusFilled"],
      less: ["", ""],
      view: ["", ""],
      edit: ["", ""],
      erase: ["tb", "TbTrashFilled"],
      card: ["", ""],
      money: ["", ""],
      close: ["", ""],
      open: ["", ""],
      upload: ["tb", "TbSquareRoundedArrowUpFilled"],
      confetti: ["", ""],
      password: ["tb", "TbLockSquareRoundedFilled"],
      chart: ["tb", "TbChartAreaLineFilled"],
      receipt: ["", ""],
      share: ["", ""],
      heart: ["tb", "TbHeartFilled"],
      id: ["", ""],
      profile: ["", ""],
      file: ["", ""],
      email: ["tb", "TbMailFilled"],
      return: ["", ""],
      qr: ["", ""],
      quote: ["", ""],
      alert: ["tb", "TbAlertTriangleFilled"],
      send: ["", ""],
      wallet: ["", ""],
      warning: ["tb", "TbAlertSquareRoundedFilled"],
      like: ["tb", "TbThumbUpFilled"],
      dislike: ["tb", "TbThumbDownFilled"],
      tag: ["", ""],
      filter: ["", ""],
      annex: ["", ""],
      calendar: ["", ""],
      calc: ["", ""],
      photo: ["", ""],
      image: ["tb", "TbPhotoFilled"],
      comment: ["", ""],
    },
    circle: {
      home: ["bi", "BiSolidHomeCircle"],
      shop: ["", ""],
      language: ["md", "MdFlagCircle"],
      arrowLeft: ["bi", "BiSolidCaretLeftCircle"],
      arrowRight: ["bi", "BiSolidCaretRightCircle"],
      search: ["hi", "HiMiniMagnifyingGlassCircle"],
      confirm: ["tb", "TbCircleCheckFilled"],
      cancel: ["", ""],
      star: ["", ""],
      product: ["", ""],
      setting: ["md", "MdBuildCircle"],
      menu: ["io5", "IoEllipsisVerticalCircleSharp"],
      list: ["io5", "IoListCircle"],
      grid: ["pi", "PiCirclesFourFill"],
      brightness: ["tb", "TbCircleDot"],
      darkness: ["tb", "TbCircleDotFilled"],
      login: ["ri", "RiLoginCircleFill"],
      logout: ["ri", "RiLogoutCircleRLine"],
      add: ["md", "MdAddCircle"],
      less: ["md", "MdRemoveCircle"],
      view: ["", ""],
      edit: ["pi", "PiPencilCircleFill"],
      erase: ["", ""],
      card: ["io5", "IoCard"],
      money: ["bi", "BiSolidDollarCircle"],
      close: ["tb", "TbCircleXFilled"],
      open: ["", ""],
      upload: ["ri", "RiArrowUpCircleFill"],
      confetti: ["", ""],
      password: ["tb", "TbCircleKeyFilled"],
      chart: ["", ""],
      receipt: ["", ""],
      share: ["", ""],
      heart: ["bi", "BiSolidHeartCircle"],
      id: ["", ""],
      profile: ["bi", "BiSolidUserCircle"],
      file: ["", ""],
      email: ["io5", "IoAtCircle"],
      return: ["io5", "IoArrowUndoCircle"],
      qr: ["", ""],
      quote: ["", ""],
      alert: ["md", "MdCircleNotifications"],
      send: ["io5", "IoArrowRedoCircle"],
      wallet: ["", ""],
      warning: ["tb", "TbAlertCircleFilled"],
      like: ["", ""],
      dislike: ["", ""],
      tag: ["", ""],
      filter: ["io5", "IoFilterCircleSharp"],
      annex: ["pi", "PiPaperclipFill"],
      calendar: ["", ""],
      calc: ["", ""],
      photo: ["", ""],
      image: ["", ""],
      comment: ["", ""],
    },
    outline: {
      home: ["ti", "TiHomeOutline"],
      shop: ["", ""],
      language: ["ti", "TiWorldOutline"],
      arrowLeft: ["ti", "TiChevronLeftOutline"],
      arrowRight: ["ti", "TiChevronRightOutline"],
      search: ["ti", "TiZoomOutline"],
      confirm: ["ti", "TiTickOutline"],
      cancel: ["ti", "TiCancelOutline"],
      star: ["ti", "TiStarOutline"],
      product: ["", ""],
      setting: ["ti", "TiCogOutline"],
      menu: ["ti", "TiThMenuOutline"],
      list: ["ti", "TiThListOutline"],
      grid: ["ti", "TiThLargeOutline"],
      brightness: ["", ""],
      darkness: ["", ""],
      login: ["", ""],
      logout: ["", ""],
      add: ["ti", "TiPlusOutline"],
      less: ["ti", "TiMinusOutline"],
      view: ["ti", "TiEyeOutline"],
      edit: ["", ""],
      erase: ["ti", "TiDeleteOutline"],
      card: ["", ""],
      money: ["", ""],
      close: ["ti", "TiTimesOutline"],
      open: ["", ""],
      upload: ["ti", "TiUploadOutline"],
      confetti: ["", ""],
      password: ["ti", "TiKeyOutline"],
      chart: ["ti", "TiChartAreaOutline"],
      receipt: ["", ""],
      share: ["", ""],
      heart: ["ti", "TiHeartOutline"],
      id: ["", ""],
      profile: ["ti", "TiUserOutline"],
      file: ["", ""],
      email: ["", ""],
      return: ["", ""],
      qr: ["", ""],
      quote: ["", ""],
      alert: ["", ""],
      send: ["ti", "TiArrowForwardOutline"],
      wallet: ["", ""],
      warning: ["ti", "TiInfoOutline"],
      like: ["", ""],
      dislike: ["", ""],
      tag: ["", ""],
      filter: ["", ""],
      annex: ["ti", "TiAttachmentOutline"],
      calendar: ["ti", "TiCalendarOutline"],
      calc: ["", ""],
      photo: ["ti", "TiCameraOutline"],
      image: ["ti", "TiImageOutline"],
      comment: ["", ""],
    },
    big: {
      home: ["", ""],
      shop: ["", ""],
      language: ["", ""],
      arrowLeft: ["", ""],
      arrowRight: ["", ""],
      search: ["", ""],
      confirm: ["", ""],
      cancel: ["", ""],
      star: ["", ""],
      product: ["", ""],
      setting: ["", ""],
      menu: ["", ""],
      list: ["", ""],
      grid: ["", ""],
      brightness: ["", ""],
      darkness: ["", ""],
      login: ["", ""],
      logout: ["", ""],
      add: ["", ""],
      less: ["", ""],
      view: ["", ""],
      edit: ["", ""],
      erase: ["", ""],
      card: ["", ""],
      money: ["", ""],
      close: ["", ""],
      open: ["", ""],
      upload: ["", ""],
      confetti: ["", ""],
      password: ["", ""],
      chart: ["", ""],
      receipt: ["", ""],
      share: ["", ""],
      heart: ["", ""],
      id: ["", ""],
      profile: ["", ""],
      file: ["", ""],
      email: ["", ""],
      return: ["", ""],
      qr: ["", ""],
      quote: ["", ""],
      alert: ["", ""],
      send: ["", ""],
      wallet: ["", ""],
      warning: ["", ""],
      like: ["", ""],
      dislike: ["", ""],
      tag: ["", ""],
      filter: ["", ""],
      annex: ["", ""],
      calendar: ["", ""],
      calc: ["", ""],
      photo: ["", ""],
      image: ["", ""],
      comment: ["", ""],
    },
    small: {
      home: ["", ""],
      shop: ["", ""],
      language: ["", ""],
      arrowLeft: ["", ""],
      arrowRight: ["", ""],
      search: ["", ""],
      confirm: ["", ""],
      cancel: ["", ""],
      star: ["", ""],
      product: ["", ""],
      setting: ["", ""],
      menu: ["", ""],
      list: ["", ""],
      grid: ["", ""],
      brightness: ["", ""],
      darkness: ["", ""],
      login: ["", ""],
      logout: ["", ""],
      add: ["", ""],
      less: ["", ""],
      view: ["", ""],
      edit: ["", ""],
      erase: ["", ""],
      card: ["", ""],
      money: ["", ""],
      close: ["", ""],
      open: ["", ""],
      upload: ["", ""],
      confetti: ["", ""],
      password: ["", ""],
      chart: ["", ""],
      receipt: ["", ""],
      share: ["", ""],
      heart: ["", ""],
      id: ["", ""],
      profile: ["", ""],
      file: ["", ""],
      email: ["", ""],
      return: ["", ""],
      qr: ["", ""],
      quote: ["", ""],
      alert: ["", ""],
      send: ["", ""],
      wallet: ["", ""],
      warning: ["", ""],
      like: ["", ""],
      dislike: ["", ""],
      tag: ["", ""],
      filter: ["", ""],
      annex: ["", ""],
      calendar: ["", ""],
      calc: ["", ""],
      photo: ["", ""],
      image: ["", ""],
      comment: ["", ""],
    },
    stylized: {
      home: ["", ""],
      shop: ["", ""],
      language: ["", ""],
      arrowLeft: ["", ""],
      arrowRight: ["", ""],
      search: ["gi", "GiMagnifyingGlass"],
      confirm: ["", ""],
      cancel: ["", ""],
      star: ["", ""],
      product: ["", ""],
      setting: ["", ""],
      menu: ["", ""],
      list: ["", ""],
      grid: ["", ""],
      brightness: ["", ""],
      darkness: ["", ""],
      login: ["", ""],
      logout: ["", ""],
      add: ["", ""],
      less: ["", ""],
      view: ["", ""],
      edit: ["", ""],
      erase: ["", ""],
      card: ["", ""],
      money: ["gi", "GiMoneyStack"],
      close: ["", ""],
      open: ["", ""],
      upload: ["", ""],
      confetti: ["gi", "GiGlassCelebration"],
      password: ["", ""],
      chart: ["", ""],
      receipt: ["", ""],
      share: ["", ""],
      heart: ["", ""],
      id: ["", ""],
      profile: ["", ""],
      file: ["", ""],
      email: ["", ""],
      return: ["", ""],
      qr: ["", ""],
      quote: ["", ""],
      alert: ["", ""],
      send: ["", ""],
      wallet: ["", ""],
      warning: ["", ""],
      like: ["", ""],
      dislike: ["", ""],
      tag: ["", ""],
      filter: ["", ""],
      annex: ["", ""],
      calendar: ["", ""],
      calc: ["", ""],
      photo: ["", ""],
      image: ["", ""],
      comment: ["", ""],
    },
    leak: {
      home: ["", ""],
      shop: ["", ""],
      language: ["", ""],
      arrowLeft: ["", ""],
      arrowRight: ["", ""],
      search: ["", ""],
      confirm: ["", ""],
      cancel: ["", ""],
      star: ["", ""],
      product: ["", ""],
      setting: ["", ""],
      menu: ["", ""],
      list: ["", ""],
      grid: ["", ""],
      brightness: ["", ""],
      darkness: ["", ""],
      login: ["", ""],
      logout: ["", ""],
      add: ["", ""],
      less: ["", ""],
      view: ["", ""],
      edit: ["", ""],
      erase: ["", ""],
      card: ["", ""],
      money: ["", ""],
      close: ["", ""],
      open: ["", ""],
      upload: ["", ""],
      confetti: ["", ""],
      password: ["", ""],
      chart: ["", ""],
      receipt: ["", ""],
      share: ["", ""],
      heart: ["", ""],
      id: ["", ""],
      profile: ["", ""],
      file: ["", ""],
      email: ["", ""],
      return: ["", ""],
      qr: ["", ""],
      quote: ["", ""],
      alert: ["", ""],
      send: ["", ""],
      wallet: ["", ""],
      warning: ["", ""],
      like: ["", ""],
      dislike: ["", ""],
      tag: ["", ""],
      filter: ["", ""],
      annex: ["", ""],
      calendar: ["", ""],
      calc: ["", ""],
      photo: ["", ""],
      image: ["", ""],
      comment: ["", ""],
    },
    color: {
      home: ["fc", "FcHome"],
      shop: ["fc", "FcShop"],
      language: ["fc", "FcGlobe"],
      arrowLeft: ["fc", "FcPrevious"],
      arrowRight: ["fc", "FcNext"],
      search: ["fc", "FcSearch"],
      confirm: ["fc", "FcCheckmark"],
      cancel: ["fc", "FcCancel"],
      star: ["fc", "FcRating"],
      product: ["fc", "FcPackage"],
      setting: ["fc", "FcSettings"],
      menu: ["fc", "FcMenu"],
      list: ["fc", "FcList"],
      grid: ["fc", "FcGrid"],
      brightness: ["fc", "FcLandscape"],
      darkness: ["fc", "FcNightLandscape"],
      login: ["fc", "FcInternal"],
      logout: ["fc", "FcExternal"],
      add: ["fc", "FcPlus"],
      less: ["fc", "FcMinus"],
      view: ["im", "ImEye"],
      edit: ["pi", "PiPencilCircleDuotone"],
      erase: ["fc", "FcEmptyTrash"],
      card: ["gi", "GiSwipeCard"],
      money: ["fc", "FcSalesPerformance"],
      close: ["sl", "SlClose"],
      open: ["", ""],
      upload: ["fc", "FcUpload"],
      confetti: ["pi", "PiConfettiDuotone"],
      password: ["fc", "FcKey"],
      chart: ["fc", "FcComboChart"],
      receipt: ["", ""],
      share: ["fc", "FcShare"],
      heart: ["fc", "FcLike"],
      id: ["fc", "FcBiotech"],
      profile: ["fc", "FcBusinesswoman"],
      file: ["fc", "FcOpenedFolder"],
      email: ["fc", "FcAddressBook"],
      return: ["fc", "FcUndo"],
      qr: ["", ""],
      quote: ["", ""],
      alert: ["fc", "FcHighPriority"],
      send: ["", ""],
      wallet: ["fc", "FcMoneyTransfer"],
      warning: ["", ""],
      like: ["", ""],
      dislike: ["", ""],
      tag: ["", ""],
      filter: ["fc", "FcFilledFilter"],
      annex: ["", ""],
      calendar: ["fc", "FcCalendar"],
      calc: ["fc", "FcCalculator"],
      photo: ["fc", "FcCompactCamera"],
      image: ["fc", "FcPicture"],
      comment: ["", ""],
    },
  };
  return Icon(values[style][name][0], values[style][name][1], size);
}

export function styleSize(base, animation, level?) {
  if (level) {
  } else {
  }
}
